name: MortisBank
version: '5.0.0'
main: com.mortisdevelopment.mortisbank.MortisBank
api-version: '1.21'
dependencies:
  server:
    MortisCore:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    EssentialsX:
      load: BEFORE
      required: false
      join-classpath: false