name: MortisBank
version: '${project.version}'
main: com.mortisdevelopment.mortisbank.MortisBank
api-version: 1.13
depend:
  - Vault
  - PlaceholderAPI
softdepend:
  - ProtocolLib
  - Essentials
commands:
  bank:
    aliases:
      - mortisbank